### ISSUE TITLE
Spring Cloud 应用中日期类型如何选择？

### ISSUE THREAD

**Issue by jast90** [jast90/java-tutorial#1]
```yml
spring:
    mvc:
        format:
            date-time: yyyy-MM-dd HH:mm:ss
            date: yyyy-MM-dd
            time: HH:mm:ss
```
Java 8
- LocalTime
- LocalDate
- LocalDateTime

MySQL 驱动也用 8
- TIME
- DATE
- DATETIME
